SS:=3;
LL:=15;
MM:=6;

DIF:100*(EMA(CLOSE,SS)-EMA(CLOSE,LL)),NODRAW;
DEA:EMA(DIF,MM),COLOR0CAEE6;
DRAWBAND(DIF,RGB(155,50,50),DEA,RGB(0,100,50));
MACD:(DIF-DEA)*2,COLORSTICK,COLORE970DC;
DRAWICON(CROSS(DIF,DEA),DEA,1);
DRAWICON(CROSS(DEA,DIF),DEA,2);

DEATH_CROSS:=CROSS(DEA,DIF);
N1:=BARSLAST(DEATH_CROSS);
N2:=REF(BARSLAST(DEATH_CROSS),N1+1);
N3:=REF(BARSLAST(DEATH_CROSS),N2+N1+2);

CL1:=LLV(C,N1+1);
DIFL1:=LLV(DIF,N1+1);
CL2:=REF(CL1,N1+1);
DIFL2:=REF(DIFL1,N1+1);
CL3:=REF(CL2,N1+1);
DIFL3:=REF(DIFL2,N1+1);
PDIFL2:=IF(DIFL2>0,INTPART(LOG(DIFL2))-1, INTPART(LOG(-DIFL2))-1);
MDIFL2:=INTPART(DIFL2/POW(10,PDIFL2));
PDIFL3:=IF(DIFL3>0,INTPART(LOG(DIFL3))-1, INTPART(LOG(-DIFL3))-1);

MDIFL3:= INTPART(DIFL3/POW(10, PDIFL3));
MDIFB2:= INTPART(DIF/POW(10,PDIFL2));
MDIFB3:= INTPART(DIF/POW(10,PDIFL3));
DIRECT_BOT_DIV:=(CL1<CL2) AND (MDIFB2>MDIFL2) AND (MACD <0 AND REF(MACD,1)<0) AND (MDIFB2<=REF(MDIFB2,1));
INDIRECT_BOT_DIV:=(CL1<CL2 AND CL3<CL2) AND (MDIFB3>MDIFL3) AND (MACD<0 AND REF(MACD,1)<0) AND MDIFB3<=REF(MDIFB3,1);

B:=(DIRECT_BOT_DIV OR INDIRECT_BOT_DIV);
BG:=((MDIFB2>REF(MDIFB2,1))*REF(DIRECT_BOT_DIV,1)) OR ((MDIFB3>REF(MDIFB3,1))*REF(INDIRECT_BOT_DIV,1));
BOT_DIV_DISAPPER:=(REF(DIRECT_BOT_DIV,1) AND DIFL1<=DIFL2) OR (REF(INDIRECT_BOT_DIV,1) AND DIFL1<DIFL3);
DRAWTEXT((B AND COUNT(B,2)=1),(DIF*1.1),'钝'),COLORYELLOW;
DRAWTEXT(FILTER(BG,10),DIF*1.1,'成'),COLORMAGENTA;
DRAWTEXT(FILTER(BOT_DIV_DISAPPER,10),DIF*1.1,'消'),COLORGREEN;


DRAWTEXT((B AND COUNT(B,2)=1),(DIF*1.5),'↑'),COLORYELLOW,LINETHICK4;
DRAWTEXT(FILTER(BG,10),DIF*1.5,'↑'),COLORMAGENTA, LINETHICK4;
DRAWTEXT(FILTER(BOT_DIV_DISAPPER,10),DIF*1.5,'↑'),COLORGREEN, LINETHICK4;

GOLDEN_CROSS:=CROSS(DIF,DEA);
M1:=BARSLAST(GOLDEN_CROSS);
M2:=REF(BARSLAST(DEATH_CROSS),M1+1);
M3:=REF(BARSLAST(DEATH_CROSS),M2+M1+2);

CH1:=LLV(C,M1+1);
DIFH1:=LLV(DIF,M1+1);
CH2:=REF(CH1,M1+1);
DIFH2:=REF(DIFH1,M1+1);
CH3:=REF(CH2,M1+1);
DIFH3:=REF(DIFH2,M1+1);
PDIFH2:=IF(DIFH2>0,INTPART(LOG(DIFH2))-1, INTPART(LOG(-DIFH2))-1);
MDIFH2:=INTPART(DIFH2/POW(10,PDIFH2));
PDIFH3:=IF(DIFH3>0,INTPART(LOG(DIFH3))-1, INTPART(LOG(-DIFH3))-1);
MDIFH3:= INTPART(DIFH3/POW(10, PDIFH3));
MDIFT2:= INTPART(DIF/POW(10,PDIFH2));
MDIFT3:= INTPART(DIF/POW(10,PDIFH3));
DIRECT_TOP_DIV:=(CH1>CH2) AND (MDIFT2<MDIFH2) AND (MACD >0 AND REF(MACD,1)>0) AND (MDIFT2>REF(MDIFT2,1));
INDIRECT_TOP_DIV:=(CH1>CH3 AND CH3>CH2) AND (MDIFT3<MDIFH3) AND (MACD>0 AND REF(MACD,1)>0) AND MDIFT3>=REF(MDIFT3,1);
T:=(DIRECT_TOP_DIV OR INDIRECT_TOP_DIV);
TG:=((MDIFT2<REF(MDIFT2,1))*REF(DIRECT_TOP_DIV,1)) OR ((MDIFT3<REF(MDIFT3,1))*REF(INDIRECT_TOP_DIV,1));
TOP_DIV_DISAPPER:=(REF(DIRECT_TOP_DIV,1) AND DIFH1>=DIFH2) OR (REF(INDIRECT_TOP_DIV,1) AND DIFH1>=DIFH3);

DRAWTEXT((T AND COUNT(T,2)=1),(DIF*1.1),'钝'),COLORYELLOW;
DRAWTEXT(FILTER(TG,20),DIF*1.1,'成'),COLORMAGENTA;
DRAWTEXT(FILTER(TOP_DIV_DISAPPER,20),DIF*1.1,'消'),COLORGREEN;

DRAWTEXT((T AND COUNT(T,2)=1),(DIF*1.5),'↓'),COLORYELLOW,LINETHICK4;
DRAWTEXT(FILTER(TG,20),DIF*1.5,'↓'),COLORMAGENTA, LINETHICK4;
DRAWTEXT(FILTER(TOP_DIV_DISAPPER,20),DIF*1.5,'↓'),COLORGREEN, LINETHICK4;
