'MACD背离。长短周期MACD背离'

SS:=12;
LL:=26;
MM:=9;
DIF:100*(EMA(CLOSE,SS)-EMA(CLOSE,LL)),COLORFF8D1E;
DEA:EMA(DIF,MM),COLOR0CAEE6;
GOLD_CROSS1:=SUMBARS(CROSS(DIF,DEA),2);
GOLD_CROSS2:=SUMBARS(CROSS(DIF,DEA),1);
DEATH_CROSS1:=SUMBARS(CROSS(DEA,DIF),2);
DEATH_CROSS2:=SUMBARS(CROSS(DEA,DIF),1);

HD1_PERIOD:=HHVBARS(DIF,GOLD_CROSS1);
HD2_PERIOD:=HHVBARS(DIF,GOLD_CROSS2);
COND1:= GOLD_CROSS1> HD1_PERIOD AND HD1_PERIOD> DEATH_CROSS1;
COND2:=REF(C, HD1_PERIOD)<REF(C,HD2_PERIOD) AND REF(DIF,HD1_PERIOD)>REF(DIF,HD2_PERIOD);
COND3:=CROSS(DEA,DIF);
COND4:=COND1 AND COND2 AND COND3;

DRAWTEXT(COND4,DIF*1.2,'顶离'),COLORGREEN;


LD1_PERIOD:=LLVBARS(DIF,GOLD_CROSS1);
LD2_PERIOD:=LLVBARS(DIF,GOLD_CROSS2);
COND5:= GOLD_CROSS1> LD1_PERIOD AND LD1_PERIOD> DEATH_CROSS1;
COND6:=REF(C, LD1_PERIOD)>REF(C,LD2_PERIOD) AND REF(DIF,LD1_PERIOD)<REF(DIF,LD2_PERIOD);
COND7:=CROSS(DEA,DIF);
COND8:=COND5 AND COND6 AND COND7;

DRAWTEXT(COND8,DIF*0.96,'底离'),COLORRED;