TYP:=(HIGH+LOW+CLOSE)/3;
CCI:(TYP-MA(TYP,70))/(0.015*AVEDEV(TYP,70))/50,COLORBLACK;

DIF:EMA(CLOSE,12)-EMA(CLOSE,26),COLORFF8D1E;
DEA:EMA(DIF,9),COLOR0CAEE6;
MACD:(DIF-DEA)*2,COLORSTICK,COLORE970DC;

COND1:=(CCI>0 AND CROSS(DIF,DEA)) OR (CROSS(CCI,0) AND REF(CROSS(DIF,DEA),1)) OR (CROSS(CCI,0));
DRAWICON(COND1,DIF,26);

COND2:=DEA<0;
COND:=COND1 AND COND2;
DRAWICON(COND,DIF,24)