RSV:=(CLOSE-LLV(LOW,P1))/(HHV(HIGH,P1)-LLV(LOW,P1))*100;
K:=SMA(RSV,P2,1);
D:=SMA(K,P3,1);
J:=3*K-2*D;


DIF:=EMA(CLOSE,SHORT)-EMA(CLOSE,LONG);
DEA:=EMA(DIF,M);
MACD:=(DIF-DEA)*2;

N:=300;
KH:=HHV(K,N);
DH:=HHV(D,N);
JH:=HHV(J,N);
KL:=LLV(K,N);
DL:=LLV(D,N);
JL:=LLV(J,N);
KDJMAX:=MAX(KH,MAX(DH,JH));
KDJMIN:=MIN(KL,MIN(DL,JL));
KDJ_M2:=(KDJMAX+KDJMIN)/2;
KDJ_A2:=(KDJMAX-KDJMIN);

DIFH:=HHV(DIF,N);
DEAH:=HHV(DEA,N);
MACDH:=HHV(MACD,N);
DIFL:=LLV(DIF,N);
DEAL:=LLV(DEA,N);
MACDL:=LLV(MACD,N);
MACDMAX:=MAX(DIFH,MAX(DEAH,MACDH));
MACDMIN:=MIN(DIFL,MIN(DEAL,MACDL));
MACD_M1:=(MACDMAX+MACDMIN)/2;
MACD_A1:=(MACDMAX-MACDMIN);

NEW_BASE:=(0-MACD_M1)*KDJ_A2/MACD_A1+KDJ_M2;
J_NEW:J-NEW_BASE,LINETHICK2,COLORRED;
DIF_NEW:(DIF-MACD_M1)*KDJ_A2/MACD_A1+KDJ_M2-NEW_BASE, COLORORANGE;
DEA_NEW:(DEA-MACD_M1)*KDJ_A2/MACD_A1+KDJ_M2-NEW_BASE, COLORBLUE;
MACD_NEW:(MACD-MACD_M1)*KDJ_A2/MACD_A1+KDJ_M2-NEW_BASE, COLORGREEN, COLORSTICK;