量:VOLA,COLORORANGE,NODRAW;

总体:=(H-L);
买入实体:=IF(C>O,C-O,0);
买入下影:=IF(C>L,MIN(O,C)-L,0);
卖出实体:=IF(C<O,O-C,0);
卖出上影:=IF(H>C,H-MAX(O,C),0);

买入:(买入实体+买入下影)/总体,COLORGREEN,NODRAW;
卖出:-(卖出实体+卖出上影)/总体,COLORRED,NODRAW;

WIDTH:=0.8;
STICKLINE(C>O,0,量,WIDTH,0),COLOR328332;{绿色}
STICKLINE(C<O,0,量,WIDTH,0),COLORRED;{棕褐色}
STICKLINE(1,0,量*买入,WIDTH,0),COLORFFFF00;{黄色}
STICKLINE(1,0,量*卖出,WIDTH,0),COLORMAGENTA;{粉红色}

MAVOL1:MA(VOLA,5),COLORFF8D1E;
MAVOL2:MA(VOLA,10),COLOR0CAEE6;
MAVOL3:MA(VOLA,20),COLORE970DC;
