VA:=IF(CLOSE>REF(CLOSE,1),VOL,IF(CLOSE<REF(CLOSE,1),-VOL,0));
OBV:SUM(VA,TOTALBARSCOUNT),COLORFFC90E;

MAOBV:=MA(OBV,25);
BB:=MAOBV>REF(MAOBV,1);
IF(BB,MAOBV,DRAWNULL),COLORRED,LINETHICK2;
IF(NOT(BB),MAOBV, DRAWNULL),COLORGREEN,LINETHICK2;

FLAG1:=BB AND REF(BB,1)=0;
FLAG2:=NOT(BB) AND REF(BB,1)=1;
IF(FLAG1,MAOBV,DRAWNULL),POINTDOT,COLORRED,LINETHICK6;
IF(FLAG2,MAOBV,DRAWNULL),POINTDOT,COLORGREEN,LINETHICK6;

COND1:=CROSS(OBV,MAOBV);
COND2:=CROSS(MAOBV,OBV);

DRAWICON(COND1,MAOBV*0.98,1);
DRAWICON(COND2,MAOBV*1.02,2);
