N:=10;
A1:=REF(C,N)=HHV(C,N*2);
B1:=FILTER(A1,N);
C1:=BACKSET(B1,N+1);
HD:=FILTER(C1,N);
BOX_TOP:=REF(H,BARSLAST(HD));

STICKLINE(C,BOX_TOP,BOX_TOP,6,0),COLORRED;


A2:=REF(C,N)=LLV(C,N*2);
B2:=FILTER(A2,N);
C2:=BACKSET(B2,N+1);
LD:=FILTER(C2,N);
BOX_BOT:=REF(L,BARSLAST(LD));

STICKLINE(C,BOX_BOT,BOX_BOT,6,0),COLORGREEN;